apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 181728646524.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googleclothes:835b0692fd4a8958dcabc23598a30e0226bbda22
        ports:
        - containerPort: 80
