apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 181728646524.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googleclothes:a67c7d1bf1ba37e68673f22f28e1665e066b2be2
        ports:
        - containerPort: 80
