apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 181728646524.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-earphones:f9a70c2f81ac43a70e8ce9aef8c42d90e021cbfa
        ports:
        - containerPort: 80
