apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 181728646524.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-earphones:205732c94a0f25f4b1999804e8327a04ebd46e29
        ports:
        - containerPort: 80
