apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 181728646524.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-earphones:a5a6be2bdce4235b0150c9bb47227708615acdaf
        ports:
        - containerPort: 80
