apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 181728646524.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-backend:70514fa11bf5ac7b057e9de1c3dcf88ed3ad5a9c
          ports:
            - containerPort: 5000
