apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 181728646524.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-backend:2dc59456d4aef3b735d7ff6d863cc539268446e8
          ports:
            - containerPort: 5000
