apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 181728646524.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-backend:98c0314262d0853b850773f747885a2f3c3bae18
          ports:
            - containerPort: 5000
