apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 181728646524.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-electronics:4f425263731ad316748d4db80179134b20ac8a98
        ports:
        - containerPort: 80
