apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 181728646524.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-main:63474aa669cbd97ef1854dae2e61b1b9c6818314
        ports:
        - containerPort: 80

