apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 181728646524.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-main:b7bf8472155ae665224936c600d5d47243a3e7e7
        ports:
        - containerPort: 80

