apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 181728646524.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-main:a67c7d1bf1ba37e68673f22f28e1665e066b2be2
        ports:
        - containerPort: 80

