apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 181728646524.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlemusic:a67c7d1bf1ba37e68673f22f28e1665e066b2be2
        ports:
        - containerPort: 80
