apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 181728646524.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlemusic:e3853802f9dcf544619b611e66c0c9ce6564998b
        ports:
        - containerPort: 80
