apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 181728646524.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlemusic:684eb530bf6cd677bf48cd09bc4caca3fa0a1fff
        ports:
        - containerPort: 80
