apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 181728646524.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-computers:205732c94a0f25f4b1999804e8327a04ebd46e29
        ports:
        - containerPort: 80
