apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 181728646524.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-phones:34ac893151b8ca637da1eb3019dce7f0b66072b0
        ports:
        - containerPort: 80
