apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 181728646524.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlegrocery:493901c51bdd3b1ef3d4f7a9fff43531705f026a
        ports:
        - containerPort: 80
